portfolio_personnel/portfolio_personnel/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('', views.groupes_list, name='groupes-list'),
    path('groupes/', views.groupes_list, name='groupes-list'),
    path('groupes/<int:groupe_id>/', views.groupe_detail, name='groupe-detail'),
    path('groupes/add/', views.creer_groupe, name="creer-groupe"),
    path('groupes/<int:groupe_id>/update/', views.modifie_groupe, name="modifie-groupe"),
    path('groupes/<int:groupe_id>/delete/', views.supprime_groupe, name="supprime-groupe"),
    path('listings/', views.listings),
    path('contact-us/', views.contactUs, name="contact"),
    path('admin/', admin.site.urls),
]

portfolio_personnel/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Groupe(models.Model):
    
    class Genre(models.TextChoices):
        HIP_HOP= "HH"
        SYNTH_POP = "SP"
        ALTERNATIVE_ROCK = "AR"
        
    nom = models.fields.CharField(max_length=100)
    
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    
    biographie = models.fields.CharField(max_length=1000)
    annee_formation = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2021)])
    actif = models.fields.BooleanField(default=True)
    page_officielle = models.fields.URLField(null=True, blank=True)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    annee = models.fields.IntegerField(null=True)
    def __str__(self):
        return f'{self.nom}'


class Article(models.Model):
    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    annee = models.fields.IntegerField()
    groupe = models.ForeignKey(Groupe, null=True, on_delete=models.SET_NULL)
    
    def __str__(self):
        return f"{self.title}"

portfolio_personnel/listings/forms.py
from django import forms
from listings.models import Groupe

class GroupeForm(forms.ModelForm):
    class Meta:
        model= Groupe
        exclude = ('actif', 'page_officielle')

class ContactUsForm(forms.Form):
    nom = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)

portfolio_personnel/listings/views.py
from django.http import HttpResponse
from listings.models import Groupe
from listings.forms import ContactUsForm, GroupeForm
from django.core.mail import send_mail
from django.shortcuts import render,redirect

def contactUs(request):
    if request.method == 'POST':
        form= ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
                subject=f' Message de {form.cleaned_data["nom"] or "anonyme"} via Merchex',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz']
            )
            return redirect('groupes-list')
    else:
        form = ContactUsForm()
    return render(request, 'listings/contact.html', {'form':form})



def groupes_list(request):
    groupes = Groupe.objects.all()
    return render(request, "listings/groupe_list.html", {'groupes': groupes} )

def groupe_detail(request, groupe_id):
    groupe = Groupe.objects.get(id=groupe_id)
    return render(request, "listings/groupe_detail.html", {"groupe": groupe})

def listings(request):
    return HttpResponse("<h1>Liste des annonces pour les articles</h1>")

def creer_groupe(request):
    if request.method == 'POST':
        form = GroupeForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Groupe » et la sauvegarder dans la BD
            groupe = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect('groupe-detail', groupe.id)
    else:
        form = GroupeForm()
    
    return render(request, 'listings/creer_groupe.html', {"form": form})

def modifie_groupe(request, groupe_id):
    groupe = Groupe.objects.get(id=groupe_id)
    if request.method == 'POST':
        form = GroupeForm(request.POST, instance=groupe)
        if form.is_valid():
            form.save()
            return redirect('groupe-detail', groupe.id)
    else:
        form = GroupeForm(instance=groupe)
    return render(request, 'listings/modifie_groupe.html',{'form':form})

def supprime_groupe(request, groupe_id):
    groupe = Groupe.objects.get(id=groupe_id)
    if request.method == "POST":
        groupe.delete()
        return redirect("groupes-list")
    return render(request, 'listings/supprime_groupe.html', {'groupe': groupe})

portfolio_personnel/listings/templates/listings/base.html
{% load static %}
<html>
  <head>
    <title>Merchex</title>
    <link rel="stylesheet" href="{% static 'listings/style.css' %}" />
  </head>
  <body>
    <nav>
      <a href="{% url "groupes-list" %}">Groupes</a>
      <a href="{% url "contact" %}">Contactez nous</a>
      <a href="">A propos</a>
    </nav>
    {% block content %}{% endblock %}
  </body>
</html>

portfolio_personnel/listings/templates/listings/contact.html
{% extends "listings/base.html" %} {% block content %}
<p>Moi Pabi, je suis là pour vous aider</p>
<form action="" method="post" novalidate>
  {% csrf_token %} {{form.as_p}}

  <input type="submit" value="Envoyer" />
</form>
{% endblock %}

portfolio_personnel/listings/templates/listings/creer_groupe.html
{% extends "listings/base.html" %} {% block content %}
<h1>Créer un nouveau groupe</h1>

<form action="" method="post" novalidate>
  {% csrf_token %} {{form.as_p}}
  <input type="submit" value="Créer" />
</form>
{% endblock %}

portfolio_personnel/listings/templates/listings/groupe_detail.html
{% extends "listings/base.html" %} {% block content %}
<h2>{{groupe.nom}}</h2>
<ul>
  <li>Genre : {{ groupe.get_genre_display }}</li>

  <li>Année de formation : {{ groupe.annee_formation }}</li>

  <li>Actif : {{ groupe.actif|yesno }}</li>

  <li>{{ groupe.page_officielle}}</li>
</ul>
<p>{{ groupe.biographie }}</p>
<a href="{% url "modifie-groupe" groupe.id%}">Modifier ce groupe</a>
--||--<a href="{% url "supprime-groupe" groupe.id%}"> Supprimer ce groupe</a>
<p><a href="{% url "groupes-list" %}">Liste des groupes</a></p>
{% endblock %}

portfolio_personnel/listings/templates/listings/groupe_list.html
{% extends "listings/base.html" %} {% block content %}

<h1>Groupes</h1>
<a href="{% url "creer-groupe" %}">Créer un nouveau  groupe</a>
<ul>
  {% for i in groupes %}
  <li>
    <a href="{% url "groupe-detail" i.id %}">{{i.nom}}</a>
    -<a href="{% url "modifie-groupe" i.id%}">[Editer]</a>
  </li>
  {% endfor %}
</ul>

{% endblock %}

portfolio_personnel/listings/templates/listings/modifie_groupe.html
{% extends "listings/base.html" %} {% block content %}
<h1>Modifier un groupe</h1>
<form action="" method="post">
  {% csrf_token %} {{form.as_p}}
  <input type="submit" value="Modifier" />
</form>
{% endblock %}

portfolio_personnel/listings/templates/listings/supprime_groupe.html
{% extends "listings/base.html" %} {% block content %}
<h1>Suppression</h1>
<p>Etes-vous sûr de vouloir supprimer le groupe: {{groupe.nom}} ?</p>
<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Supprimer" />
</form>
{% endblock %}